version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:12.2.0

    working_directory: ~/project

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install packages
          command: yarn ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run Tests
          command: |
            yarn test-e2e:local

workflows:
  wdio-e2e-workflow:
    jobs:
      - test
